export interface TerminalItem {
  text: string;
  isCert?: boolean;
  certNameLength?: number;
}

export const STEP_LINES: Record<number, TerminalItem[]> = {
  1: [
    { text: '> load certifications_matrix' },
    { text: '' },
    { text: 'System processing...' },
    { text: 'Verifying academic records...' },
    { text: 'Verifying platform credentials...' },
    { text: 'Indexing learning history...' },
    { text: 'Classification complete.' },
    { text: '' },
    { text: '--------------------------------------------------' },
    { text: '' },
    { text: '[CERTIFICATIONS MATRIX]' },
    { text: '' },
    { text: 'Detected domains:' },
    { text: '→ Marketing / Analytics' },
    { text: '→ Advertising' },
    { text: '→ AI / Generative AI / Systems' },
    { text: '→ Enterprise AI / Ecosystem' },
    { text: '' }
  ],
  2: [
    { text: '---' },
    { text: '' },
    { text: '[MARKETING / ANALYTICS]' },
    { text: '' },
    { text: 'Digital Marketing Specialisation                 University of Illinois', isCert: true, certNameLength: 32 },
    { text: 'Marketing Analytics                              University of Virginia', isCert: true, certNameLength: 19 },
    { text: 'Customer Analytics                               Wharton Online', isCert: true, certNameLength: 18 },
    { text: 'Success                                          Wharton Online', isCert: true, certNameLength: 7 },
    { text: 'Digital Business Models                          Lund University', isCert: true, certNameLength: 23 },
    { text: 'Visualization with Tableau                       University of California', isCert: true, certNameLength: 26 },
    { text: '' }
  ],
  3: [
    { text: '---' },
    { text: '' },
    { text: '[ADVERTISING]' },
    { text: '' },
    { text: 'Microsoft Advertising Search Certification       Microsoft Advertising', isCert: true, certNameLength: 42 },
    { text: 'Microsoft Advertising Display & Video            Microsoft Advertising', isCert: true, certNameLength: 37 },
    { text: 'Microsoft Advertising Retail Certification       Microsoft Advertising', isCert: true, certNameLength: 42 },
    { text: 'Microsoft Advertising Certified Professional     Microsoft Advertising', isCert: true, certNameLength: 44 },
    { text: '' },
    { text: 'X Ads Manager Fundamentals                       X Ads Academy', isCert: true, certNameLength: 26 },
    { text: 'X Website Traffic & Sales Campaigns              X Ads Academy', isCert: true, certNameLength: 35 },
    { text: '' },
    { text: 'LinkedIn Marketing Strategy                      LinkedIn Marketing Labs', isCert: true, certNameLength: 27 },
    { text: '' },
    { text: 'Google Ads Search Certification                  Google', isCert: true, certNameLength: 31 },
    { text: 'Google Ads Display Certification                 Google', isCert: true, certNameLength: 32 },
    { text: 'Google Analytics Certification                   Google', isCert: true, certNameLength: 30 },
    { text: '' }
  ],
  4: [
    { text: '---' },
    { text: '' },
    { text: '[AI / GENERATIVE AI / SYSTEMS]' },
    { text: '' },
    { text: 'The Data Scientist’s Toolbox                     Johns Hopkins University', isCert: true, certNameLength: 28 },
    { text: 'Introduction to Generative AI                    Google Cloud Training', isCert: true, certNameLength: 29 },
    { text: 'Prompt Engineering for ChatGPT                   Vanderbilt University', isCert: true, certNameLength: 30 },
    { text: 'Generative AI for Developer Learning Path        Google Cloud Training', isCert: true, certNameLength: 41 },
    { text: 'Generative AI Explorer (Agent Platform)          Google Cloud', isCert: true, certNameLength: 39 },
    { text: '' },
    { text: 'Introduction to Image Generation                 Google Cloud', isCert: true, certNameLength: 32 },
    { text: 'Attention Mechanism                              Google Cloud', isCert: true, certNameLength: 19 },
    { text: 'Encoder-Decoder Architecture                     Google Cloud', isCert: true, certNameLength: 28 },
    { text: 'Introduction to Vertex AI Studio                 Google Cloud', isCert: true, certNameLength: 32 },
    { text: 'Transformer Models and BERT                      Google Cloud', isCert: true, certNameLength: 27 },
    { text: '' }
  ],
  5: [
    { text: '---' },
    { text: '' },
    { text: '[ENTERPRISE AI / ECOSYSTEM]' },
    { text: '' },
    { text: 'Introduction to AI Landing Zones                 Microsoft', isCert: true, certNameLength: 32 },
    { text: 'AI Workload Operations (AI CoE)                  Microsoft', isCert: true, certNameLength: 31 },
    { text: 'Introduction to AI Center of Excellence          Microsoft', isCert: true, certNameLength: 39 },
    { text: 'Responsible AI with GitHub Copilot               Microsoft', isCert: true, certNameLength: 34 },
    { text: 'AI Center of Excellence                          Microsoft', isCert: true, certNameLength: 23 },
    { text: '' },
    { text: 'AI Applications & Agents on Azure                Microsoft', isCert: true, certNameLength: 32 },
    { text: 'Build AI Agents (Microsoft 365 Copilot)          Microsoft', isCert: true, certNameLength: 39 },
    { text: 'Extend Microsoft 365 Copilot Studio              Microsoft', isCert: true, certNameLength: 35 },
    { text: '' }
  ],
  6: [
    { text: '---' },
    { text: '' },
    { text: '>>> End of Certifications' },
    { text: '' },
    { text: 'Certification matrix loaded successfully.' },
    { text: '' },
    { text: 'You can restart the system,' },
    { text: 'connect with me,' },
    { text: 'or continue exploring the journey.' },
    { text: '' },
    { text: '>>> type: restart | connect | explore' },
    { text: '' },
    { text: 'If explore:' },
    { text: '' },
    { text: '1. Origin Story' },
    { text: '2. Career Evolution' },
    { text: '3. From Marketing to AI Transformation Journey' },
    { text: '' }
  ]
};
